/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import data_access.Database;
import java.awt.Component;
import java.awt.GridLayout;
import java.util.LinkedList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author German le yo
 */
public class MainPanel extends javax.swing.JFrame {

    private Component[] adminComponents;
    private JTextField[] procTextFields;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        tablesTables.getTableHeader().setReorderingAllowed(false);
        tablesViews.getTableHeader().setReorderingAllowed(false);
        
        adminComponents = new Component[]{create_button};
        if(!databaseinterface.DatabaseInterface.user.isAdmin){
            for (Component adminComponent : adminComponents) {
                adminComponent.setVisible(false);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        combobox_table = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesTables = new javax.swing.JTable();
        create_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tableInfoLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        combobox_view = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablesViews = new javax.swing.JTable();
        create_button1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        combobox_view1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablesViews1 = new javax.swing.JTable();
        create_button2 = new javax.swing.JButton();
        proceduresInput = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combobox_table.setModel(new javax.swing.DefaultComboBoxModel<>(databaseinterface.DatabaseInterface.user.selectTables));
        combobox_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_tableActionPerformed(evt);
            }
        });

        tablesTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablesTables);

        create_button.setText("Create");
        create_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_buttonActionPerformed(evt);
            }
        });

        jButton1.setText("Borrar Seleccionado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableInfoLabel.setText("Buenos Dias");

        jButton2.setText("Actualizar Seleccionado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox_table, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tableInfoLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(create_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combobox_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_button)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(tableInfoLabel))
        );

        jTabbedPane1.addTab("Tablas", jPanel1);

        combobox_view.setModel(new javax.swing.DefaultComboBoxModel<>(databaseinterface.DatabaseInterface.user.selectVistas));
        combobox_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_viewActionPerformed(evt);
            }
        });

        tablesViews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablesViews);

        create_button1.setText("Create");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox_view, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create_button1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combobox_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_button1)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vistas", jPanel6);

        combobox_view1.setModel(new javax.swing.DefaultComboBoxModel<>(databaseinterface.DatabaseInterface.user.proc));
        combobox_view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_view1ActionPerformed(evt);
            }
        });

        tablesViews1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablesViews1);

        create_button2.setText("Ejecutar");

        javax.swing.GroupLayout proceduresInputLayout = new javax.swing.GroupLayout(proceduresInput);
        proceduresInput.setLayout(proceduresInputLayout);
        proceduresInputLayout.setHorizontalGroup(
            proceduresInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        proceduresInputLayout.setVerticalGroup(
            proceduresInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proceduresInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(combobox_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(create_button2)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_view1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_button2))
                .addGap(18, 18, 18)
                .addComponent(proceduresInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Procedimientos", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_viewActionPerformed
        databaseinterface.DatabaseInterface.createTableViews(combobox_view.getSelectedIndex());
    }//GEN-LAST:event_combobox_viewActionPerformed

    private void combobox_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_tableActionPerformed
        databaseinterface.DatabaseInterface.createTableTables(combobox_table.getSelectedIndex());
    }//GEN-LAST:event_combobox_tableActionPerformed

    private void create_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_buttonActionPerformed
        new ParamDialog().setVisible(true);
    }//GEN-LAST:event_create_buttonActionPerformed

    private void combobox_view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_view1ActionPerformed
        String[] newLabels = Database.getProcByName(combobox_view1.getSelectedItem().toString()).parametros;
       
        
        proceduresInput.removeAll();
        proceduresInput.setLayout(new GridLayout(newLabels.length, 1));
        
        LinkedList<JTextField> lista = new LinkedList();
        ParamDialog.PanelAttribute tmp;
        for (String newLabel : newLabels) {
            tmp = new ParamDialog.PanelAttribute(newLabel);
            proceduresInput.add(tmp);
            lista.add(tmp.textField);
        }
        
        procTextFields = lista.toArray(new JTextField[lista.size()]);
        
        setSize(500, 180 + 40 * newLabels.length);
        setLocationRelativeTo(null);
        revalidate();
        repaint();
    }//GEN-LAST:event_combobox_view1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] values = new String[tablesTables.getColumnCount()];
        int selected = tablesTables.getSelectedRow();
        for (int i = 0; i < values.length; i++) {
            values[i] = tablesTables.getValueAt(selected, i).toString();
        }
        
        databaseinterface.DatabaseInterface.delete(combobox_table.getSelectedIndex(), values);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int index = combobox_table.getSelectedIndex();
        
        String[] values = new String[tablesTables.getColumnCount()];
        int selected = tablesTables.getSelectedRow();
        for (int i = 0; i < values.length; i++) {
            values[i] = tablesTables.getValueAt(selected, i).toString();
        }
        
        new ParamDialog(index, values).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setTableModelInTables(String[][] vals, String[] titles){
        TableModel model = init(vals, titles);
        tablesTables.setModel(model);
    }
    
    public void setTableModelInViews(String[][] vals, String[] titles){
        TableModel model = init(vals, titles);
        tablesViews.setModel(model);
    }
    
    public void setTableInfoText(String info){
        tableInfoLabel.setText(info);
    }
    
    private static TableModel init(String[][] vals, String[] titles){
        return new DefaultTableModel(vals, titles){
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_table;
    private javax.swing.JComboBox<String> combobox_view;
    private javax.swing.JComboBox<String> combobox_view1;
    private javax.swing.JButton create_button;
    private javax.swing.JButton create_button1;
    private javax.swing.JButton create_button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel proceduresInput;
    private javax.swing.JLabel tableInfoLabel;
    private javax.swing.JTable tablesTables;
    private javax.swing.JTable tablesViews;
    private javax.swing.JTable tablesViews1;
    // End of variables declaration//GEN-END:variables
}
